version: '3'

services:
  db:
    # build: .
    image: 'postgres:latest'
    container_name: db
    ports:
      - 5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    volumes:
      - ./data/init.sql:/docker-entrypoint-initdb.d/10-init.sql
    restart: always

  api:
    container_name: api
    build: ./api
    ports:
      - 8000:8000
    restart: always
    links:
      - db
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - db

  web:
    container_name: web
    build: ./web
    ports:
      - 80:80
    restart: always
    depends_on:
      - api
